name: Deploying Lambdas
on:
  push:
    branches:
      - main
jobs:
  deploy_lambda1:
    name: deploying lambda1
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 13
      - name: npm install and build
        run: |
            cd lambda
            npm install
            npm run build --if-present
        env:
            CI: true   
      - name: Configure AWS credentials       
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Zip the code     
        run: zip -j lambda1.zip ./lambda/*
      - name: Update the lambda  
        run: aws lambda update-function-code --function-name=freelanceLambda --zip-file=fileb://lambda1.zip
